name: reflection_effect
description: "Reflectable is a Flutter package that provides a customizable widget designed to create a reflective effect on its child widget, is inspired by CSS box-reflect."
version: 1.0.3
homepage: https://github.com/franklin83diaz/reflection

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:


